"""empty message

Revision ID: 2c01989a7198
Revises: d42ad9ce800b
Create Date: 2020-05-12 01:20:37.950602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c01989a7198'
down_revision = 'd42ad9ce800b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('plan_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_categories', 'plan_code')
    # ### end Alembic commands ###
