"""empty message

Revision ID: 580a92e0e0df
Revises: 6d83bed0c5cc
Create Date: 2020-05-03 21:19:09.678140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580a92e0e0df'
down_revision = '6d83bed0c5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_logs', sa.Column('note', sa.Text(), nullable=True))
    op.alter_column('payment_logs', 'payment_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payment_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payment_logs', 'payment_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('payment_logs', 'note')
    # ### end Alembic commands ###
