"""empty message

Revision ID: 6d83bed0c5cc
Revises: 7608ba74c992
Create Date: 2020-05-03 20:49:00.686710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d83bed0c5cc'
down_revision = '7608ba74c992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'network')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('network', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
