"""empty message

Revision ID: d42ad9ce800b
Revises: 14ba2fbbe50e
Create Date: 2020-05-11 01:26:25.861601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd42ad9ce800b'
down_revision = '14ba2fbbe50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msisdn', sa.String(length=15), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.Enum('MTN', 'Paystack', name='paymentmodeenum'), nullable=True),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'PURCHASE', name='paymenttypeenum'), nullable=True),
    sa.Column('txn_reference', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Paid', 'Unpaid', name='statusenum'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payment_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('msisdn', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('txn_reference', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name='payment_logs_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='payment_logs_product_id_fkey'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name='payment_logs_subscriber_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_logs_pkey')
    )
    op.drop_table('transaction_items')
    op.drop_table('transactions')
    # ### end Alembic commands ###
